version: "3.8"

services:
  api:
    image: dhiway/api-server:latest
    container_name: api
    environment:
      - MNEMONIC=${AGENT_MNEMONIC}
      - PORT=${AGENT_PORT}
      - TYPEORM_HOST=${STUDIO_TYPEORM_HOST}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_USERNAME=${STUDIO_TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${STUDIO_TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${STUDIO_TYPEORM_DATABASE}
      - TYPEORM_AUTO_SCHEMA_SYNC=${STUDIO_TYPEORM_AUTO_SCHEMA_SYNC}
      - TYPEORM_ENTITIES=${STUDIO_TYPEORM_ENTITIES}
      - TYPEORM_SUBSCRIBERS=${STUDIO_TYPEORM_SUBSCRIBERS}
      - TYPEORM_MIGRATIONS=${STUDIO_TYPEORM_MIGRATIONS}
      - TYPEORM_ENTITIES_DIR=${STUDIO_TYPEORM_ENTITIES_DIR}
      - TYPEORM_MIGRATIONS_DIR=${STUDIO_TYPEORM_MIGRATIONS_DIR}
      - TYPEORM_SUBSCRIBERS_DIR=${STUDIO_TYPEORM_SUBSCRIBERS_DIR}
      - TYPEORM_LOGGING=${STUDIO_TYPEORM_LOGGING}
      - CORD_WSS_URL=ws://172.20.0.1:9944
      - ANCHOR_URI=${ANCHOR_URI}
      - DEBUG=*
    ports:
      - ${AGENT_PORT}:${AGENT_PORT}
    depends_on:
      - postgres8
    networks:
      - local8
    command: npm run prod

  postgres8:
    image: postgres:15-alpine
    container_name: postgres8
    environment:
      POSTGRES_USER: ${STUDIO_TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${STUDIO_TYPEORM_PASSWORD}
      POSTGRES_DB: ${STUDIO_TYPEORM_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${STUDIO_TYPEORM_PORT}:${TYPEORM_PORT}
    restart: always
    volumes:
      - postgres-data8:/var/lib/postgresql/data
    networks:
      - local8

volumes:
  postgres-data8:
    name: postgres-data8

networks:
  local8:
    name: local8
